version: 0.1-{build}
environment:
  Platform: Win32
  matrix:
  - PlatformToolset: Default
    Configuration: Release

install:
  - cmd: git submodule update --init --recursive
  - ps: Start-Process -FilePath "python" -ArgumentList "-m ensurepip"

  - py -3 -m pip install msgpack-python pytest chippy pywinauto


artifacts:
  - path: foo_rpc*.fb2k-component
    name: foo_rpc

build_script:
- ps: >-
    $foobar_link = "https://www.dropbox.com/s/zymo8qgoyzflhs2/foobar2000.zip?dl=1"

    Invoke-WebRequest -Uri $foobar_link -OutFile foobar.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    $zip_path = Join-Path $pwd "foobar.zip"

    $portable_test = "C:\\Projects\\foo-rpc\\portable_test"

    mkdir $portable_test

    [System.IO.Compression.ZipFile]::ExtractToDirectory($zip_path, $portable_test)

    $toolset = If ($Env:PlatformToolset -ne "Default") {"/p:PlatformToolset=" + $Env:PlatformToolset} Else {""}

    dir $portable_test

    $command = 'msbuild "foo_rpc.sln" /m /verbosity:normal /p:Configuration=Release /p:Platform="X86" `
                /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

    iex $command

    $host.SetShouldExit($LASTEXITCODE)

after_build:
  - ps: 7z a foo_rpc-$ENV:APPVEYOR_BUILD_VERSION.zip .\Release\foo_rpc.dll
  - ps: mv foo_rpc-$ENV:APPVEYOR_BUILD_VERSION.zip foo_rpc-$ENV:APPVEYOR_BUILD_VERSION.fb2k-component

before_test:
  - ps: Start-Process C:\\Projects\\foo-rpc\\portable_test\\foobar2000.exe
  - py -3 C:\\Projects\\foo-rpc\\ci\\set_driver_output.py

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


test_script:

  - 'py -3 -m pytest tests'
  - tasklist

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_success:
  - ps: appveyor PushArtifact foo_rpc-$ENV:APPVEYOR_BUILD_VERSION.fb2k-component

deploy:
- provider: BinTray
  on:
    branch: master
    appveyor_repo_tag: true
  username: PCManticore
  api_key:
    secure: gD4t00YJoTUyIEQMr/4ssXgo0PZkqNtdFa1cgUkFPQM7EPhQSHmJKwpJG1OLH2WJ
  subject: pcmanticore
  repo: foo_rpc
  package: foo_rpc
  publish: true
  override: true
