version: 1.0.{build}
environment:
  Platform: Win32
  matrix:
  - PlatformToolset: Default
    Configuration: Release
install:
- cmd: git submodule update --init --recursive
artifacts:
  - path: foo_rpc-{build}.zip
    name: foo_rpc
build_script:
- ps: >-
    $toolset = If ($Env:PlatformToolset -ne "Default") {"/p:PlatformToolset=" + $Env:PlatformToolset} Else {""}

    $command = 'msbuild "foo_rpc.sln" /m /verbosity:normal /p:Configuration=Release /p:Platform="X86" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

    iex $command

    $host.SetShouldExit($LASTEXITCODE)

on_success:
  - ps: 7z Release\foo_rpc.dll foo_rpc-{build}.zip
  - ps: appveyor PushArtifact foo_rpc-{build}.zip

deploy:
- provider: BinTray
  username: PCManticore
  api_key:
    secure: gD4t00YJoTUyIEQMr/4ssXgo0PZkqNtdFa1cgUkFPQM7EPhQSHmJKwpJG1OLH2WJ
  subject: pcmanticore
  repo: foo_rpc
  package: foo_rpc
  publish: true
  override: true
  explode: true

