version: 1.0.{build}
environment:
  Platform: Win32
  matrix:
  - PlatformToolset: Default
    Configuration: Release
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: >-
    $toolset = If ($Env:PlatformToolset -ne "Default") {"/p:PlatformToolset=" + $Env:PlatformToolset} Else {""}

    $command = 'msbuild "foo_rpc.sln" /m /verbosity:normal /p:Configuration=Release /p:Platform="X86" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

    iex $command

    $host.SetShouldExit($LASTEXITCODE)